# Generated by Django 4.2.5 on 2023-12-21 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(help_text='Enter a type', verbose_name='Type of school')),
                ('address', models.TextField(help_text='Enter an address', verbose_name='Address')),
                ('rating', test_django.models.IntegerRangeField(help_text='Choose a rating', verbose_name='0 to 10')),
            ],
            options={
                'db_table': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a first name', max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(help_text='Enter a surname', max_length=50, verbose_name='Surname')),
                ('phone_number', models.CharField(help_text='Enter a phone number', max_length=20, verbose_name='Phone Number')),
                ('id_user', models.ForeignKey(blank=True, help_text='Choose an id user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id User')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a first name', max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(help_text='Enter a surname', max_length=50, verbose_name='Surname')),
                ('experience', test_django.models.IntegerRangeField(help_text='Choose an experience', verbose_name='Experience')),
                ('id_user', models.ForeignKey(blank=True, help_text='Choose an id user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id User')),
                ('school', models.ForeignKey(help_text='Choose a school', on_delete=django.db.models.deletion.CASCADE, to='test_django.school', verbose_name='School')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=50, verbose_name='Name')),
                ('mark', test_django.models.IntegerRangeField(help_text='Enter a mark', verbose_name='Mark')),
                ('student', models.ForeignKey(help_text='Choose a student', on_delete=django.db.models.deletion.CASCADE, to='test_django.student', verbose_name='Student')),
                ('teacher', models.ForeignKey(help_text='Choose a teacher', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.teacher', verbose_name='Teacher')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
