# Generated by Django 4.2.5 on 2023-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ManyToManyField(help_text='Choose a school', to='test_django.school', verbose_name='School'),
        ),
    ]
